---
- name: Setup Raspberry Pi NTP Server
  hosts: raspberrypi
  become: true

  tasks:
    - name: Update apt package index
      ansible.builtin.apt:
        update_cache: true
        upgrade: true

    - name: Install dependencies
      ansible.builtin.apt:
        pkg:
          - pps-tools
          - gpsd
          - gpsd-clients
          - python3-gps
          - chrony
          - ufw
        state: latest

    - name: Enable UFW
      community.general.ufw:
        state: enabled

    - name: Allow SSH through UFW
      community.general.ufw:
        rule: limit
        port: ssh
        proto: tcp

    - name: Enable UFW to allow NTP from anywhere
      community.general.ufw:
        rule: allow
        port: ntp

    - name: Configure GPIO and module info for PPS
      block:
        - name: Add PPS GPIO overlay to /boot/firmware/config.txt
          ansible.builtin.lineinfile:
            path: /boot/firmware/config.txt
            line: "{{ item }}"
            state: present
          loop:
            - "# the next 3 lines are for GPS PPS signals"
            - "dtoverlay=pps-gpio,gpiopin=18"
            - "enable_uart=1"
            - "init_uart_baud=9600"

    - name: Add pps-gpio module to /etc/modules
      ansible.builtin.lineinfile:
        path: /etc/modules
        line: "pps-gpio"
        state: present

    - name: Update /etc/default/gpsd configuration
      ansible.builtin.lineinfile:
        path: /etc/default/gpsd
        regexp: '^DEVICES='
        line: 'DEVICES="/dev/ttyS0 /dev/pps0"'
      with_items:
        - 'GPSD_OPTIONS="-n"'
        - 'USBAUTO="true"'
        - 'START_DAEMON="true"'

    - name: Comment out chrony 'pool' config
      ansible.builtin.lineinfile:
        path: /etc/chrony/chrony.conf
        regexp: '^pool'
        line: '# &'

    - name: Update chrony configuration
      ansible.builtin.lineinfile:
        path: /etc/chrony/chrony.conf
        line: "{{ item }}"
        state: present
      loop:
        - 'refclock SHM 0 refid NMEA offset 0.210 precision 1e-3 poll 3 noselect'
        - 'refclock PPS /dev/pps0 refid PPS lock NMEA poll 3 prefer'
        - 'local stratum 1'
        - 'allow 192.168.5.0/24'
        - 'server time.nist.gov'
        - 'server time.cloudflare.com iburst'
        - 'server time.apple.com iburst'
        - 'server tick.usno.navy.mil'
        - 'server tock.usno.navy.mil'


    - name: Restart chrony service
      ansible.builtin.service:
        name: chrony
        state: restarted

    - name: Reboot the system
      ansible.builtin.reboot:
